In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# 데이터 준비
credit_df = pd.read_csv('data-files/credit_train4.csv', encoding='utf-8')

In [3]:
credit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   Unnamed: 0              100000 non-null  int64  
 1   Loan Status             100000 non-null  int64  
 2   Current Loan Amount     100000 non-null  float64
 3   Term                    100000 non-null  int64  
 4   Annual Income           100000 non-null  float64
 5   Credit Average          100000 non-null  int64  
 6   Credit Good             100000 non-null  int64  
 7   Credit Very Good        100000 non-null  int64  
 8   HaveMortgage            100000 non-null  int64  
 9   Home Mortgage           100000 non-null  int64  
 10  Own Home                100000 non-null  int64  
 11  Rent                    100000 non-null  int64  
 12  Emp Level Jr.           100000 non-null  int64  
 13  Emp Level Mid           100000 non-null  int64  
 14  Emp Level Senior     

In [4]:
# 저장할 때 index 컬럼을 제거하지 않은 경우 실행
# credit_df.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
# 아직 정리되지 않은 Annual Income, Current Loan Amount 컬럼 제거
# credit_df.drop(['Current Loan Amount', 'Annual Income'], axis=1, inplace=True)

In [6]:
credit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Loan Status             100000 non-null  int64
 1   Term                    100000 non-null  int64
 2   Credit Average          100000 non-null  int64
 3   Credit Good             100000 non-null  int64
 4   Credit Very Good        100000 non-null  int64
 5   HaveMortgage            100000 non-null  int64
 6   Home Mortgage           100000 non-null  int64
 7   Own Home                100000 non-null  int64
 8   Rent                    100000 non-null  int64
 9   Emp Level Jr.           100000 non-null  int64
 10  Emp Level Mid           100000 non-null  int64
 11  Emp Level Senior        100000 non-null  int64
 12  Major Credit Problem    100000 non-null  int64
 13  No Credit Problem       100000 non-null  int64
 14  Some Credit Problem     100000 non-null  int64
 15  E

In [7]:
# 데이터를 target, features로 분할
X = credit_df.drop("Loan Status", axis=1)
y = credit_df['Loan Status']

In [8]:
y.value_counts()

0    77361
1    22639
Name: Loan Status, dtype: int64

In [9]:
# 훈련 데이터와 테스트 데이터로 분할

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [14]:
X_train.shape, y_train.value_counts()

pandas.core.frame.DataFrame

In [12]:
# 모델 만들기 + 모델 훈련 : KNN
from sklearn.neighbors import KNeighborsClassifier

n = int(X_train.shape[1] / 2)
knn = KNeighborsClassifier(n_neighbors=n)

knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=11)

In [13]:
# 모델 평가
knn.score(X_train, y_train), knn.score(X_test, y_test)

(0.7661714285714286, 0.7644333333333333)

In [18]:
# 예측
predicted_values = knn.predict(X_test.values[:10])
print(predicted_values)
print(y_test.values[:10])

[0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 1 0 0 0 0 0]


In [27]:
# 모델 만들기 + 모델 훈련 : Logistic Regression

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

LogisticRegression(C=100000000)

In [28]:
# 평가
logreg.score(X_train, y_train), logreg.score(X_test, y_test)

(0.7736285714285714, 0.7736)

In [29]:
# 예측
predicted_values = logreg.predict(X_test.values[:10])
print(predicted_values)
print(y_test.values[:10])

[0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 1 0 0 0 0 0]


In [30]:
# 모델 만들기 + 모델 훈련 : SVC

from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train, y_train)

SVC()

In [31]:
# 평가
svc.score(X_train, y_train), svc.score(X_test, y_test)

(0.7736142857142857, 0.7736)

In [ ]:
# 예측
predicted_values = logreg.predict(X_test.values[:10])
print(predicted_values)
print(y_test.values[:10])